#!/bin/bash

ENV_FILE=./.env
DOCKER_COMPOSE_FILE=./docker/docker-compose.yaml
DOCKER_PROJECT_NAME=iseokchan5

set_dev_secrets() {
    local target=${1:-all}

    case $target in
        all)
            set_dev_secrets db
        ;;
        db)
            export POSTGRES_PORT=5432
            export POSTGRES_DATABASE=iseokchan
            export POSTGRES_USER=ichan_master
            export POSTGRES_PASSWORD=ichan
            export DATABASE_URL=postgresql://ichan_master:ichan@db:${POSTGRES_PORT}/iseokchan
        ;;
        *)
        error "Unknown secret" "$@"
        return 1
        ;;
    esac
}

iseokchan() {
    yarn workspace iseokchan "$@"
}

dev() {
    set_dev_secrets

    local target=${1:-all}

    case $target in
        all)
            iseokchan dev
        ;;
        migrate)
            iseokchan prisma migrate dev "${@:2}"
        ;;
        studio)
            iseokchan prisma studio
        ;;
        yarn)
            iseokchan "${@:2}"
        ;;
        build) 
            build
            ;;
        up)
            up
        ;;
        down)
            down
        ;;
        start)
            start
        ;;
        stop)
            stop
        ;;
        *)
        error "Unknown command" "$@"
        return 1
        ;;
    esac
}

test() {
    iseokchan test
}

build() {
    docker build -f "docker/Dockerfile" -t iseokchan5:latest "$@" .
}

check_db() {
    if ! db_isready ; then
        error "Database is not running"
        yarn retry -t 1000 --max-timeout=60000 ./ichan db_isready && check_db
    fi
}

up() {
    docker-compose --file="$DOCKER_COMPOSE_FILE" -p="$DOCKER_PROJECT_NAME" --profile dev up -d
}

down() {
    docker-compose --file="$DOCKER_COMPOSE_FILE" -p="$DOCKER_PROJECT_NAME" --profile dev down
}

start() {
    docker-compose --file="$DOCKER_COMPOSE_FILE" -p="$DOCKER_PROJECT_NAME" --profile dev start -d
}

stop() {
    docker-compose --file="$DOCKER_COMPOSE_FILE" -p="$DOCKER_PROJECT_NAME" --profile dev stop
}

db_isready() {
    docker exec iseokchan5_db pg_isready
}


error() {
    echo -e "\033[31mERROR\033[0m" "$@"
}

eslint() {
    iseokchan eslint --max-warnings=0 "**/*.{js,jsx,ts,tsx}" "$@"
}

stylelint() {
    iseokchan stylelint "**/*.{js,jsx,ts,tsx}" "$@"
}

fmt() {
    pipenv run black .
    iseokchan prettier --write "**/*.+(js|jsx|ts|tsx)"
}

if [ "$#" -eq "0" ]; then
    exit 1
fi

eval "$@"