
server:
  port: 8080

spring:
  sql:
    init:
      platform: postgres

  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iseokchan
    username: ichan_master
    password: ichan

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: com.iseokchan.iseokchan5.strategy.IchNameStrategy
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations: classpath*:graphql/**/

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: TRACE
