version: '3.9'
services:
  db:
    image: postgres
    container_name: iseokchan5_db
    profiles:
      - dev
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=GMT+2
      - PGTZ=GMT+2
    ports:
      - ${POSTGRES_PORT}:5432