# Generated by Django 4.1.2 on 2022-10-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iseok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="이메일")),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="인증 토큰"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="인증 IP 주소"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="인증 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="인증 요청 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Email Verification",
                "verbose_name_plural": "User Email Verifications",
                "db_table": "user_email_verification",
            },
        ),
    ]
