name: On Pull Request (Next.js)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - unlocked

jobs:
  install-node-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

  run-eslint-and-stylelint:
    runs-on: ubuntu-latest
    needs: install-node-dependencies

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Run eslint
        run: ./ichan eslint

      - name: Run stylelint
        run: ./ichan stylelint

  run-next-tests:
    runs-on: ubuntu-latest
    needs: install-node-dependencies

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Run test for next.js
        run: ./ichan test

  build-next-app:
    runs-on: ubuntu-latest
    needs: install-node-dependencies

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Build Next App
        run: ./ichan build
